### ISSUE TITLE
Enabling Komf Userscript makes the metrics screen on Komga weird.

### ISSUE THREAD

**Issue by realFPS** [Snd-R/komf-userscript#11]
With Komf script enabled.
![image](https://github.com/Snd-R/komf-userscript/assets/77321589/6b430c58-0181-4ac3-b842-6df2240c0ba6)

With Komf script disabled.
![image](https://github.com/Snd-R/komf-userscript/assets/77321589/de942a50-eea5-47ea-a8e6-21a1005d6d2f)

**Comment by Snd-R** [comment]
fixed in https://github.com/Snd-R/komf-userscript/commit/4a8c84dec6479ebe4d52f14efff4838a146bb80d
