### ISSUE TITLE
Kavita Intergraion broken with localization update 

### ISSUE THREAD

**Issue by DieselTech** [Snd-R/komf-userscript#12]
Since Kavita started doing localization the userscript has been broken. Keeping the script active in tampermonkey while loading kavita causes very slow loads and sometimes even malformed page loads. The puzzle icon shows up still, but the icon for identifying series is not present anymore. 

![image](https://github.com/Snd-R/komf-userscript/assets/30128380/8640a933-8b92-4efa-adb3-186df3ead74f)

**Comment by majora2007** [comment]
Fixed via #13
