### ISSUE TITLE
Not working in Safari v17.1

### ISSUE THREAD

**Issue by mgrimace** [Snd-R/komf-userscript#15]
Hello,

I managed to get the Komf docker working with Komga and Kavita support. I am able to use the userscript in Chrome, but it is not working or appearing for me in Safari.

Here's what I see in the developer console:

<img width="1780" alt="Screen Shot 2023-11-30 at 12 47 23 PM" src="https://github.com/Snd-R/komf-userscript/assets/55518507/1fcd6651-902c-4141-aa73-43e372a559fe">

I'm not particularly knowledgeable in userscripts/coding, if there's anything else you need please let me know.

**Comment by lnlyssg** [comment]
I've found a fix for this based on this post https://stackoverflow.com/questions/40091136/cant-create-duplicate-variable-that-shadows-a-global-property. I changed `browser` to `Browser` and it now works OK in Safari.

**Comment by mgrimace** [comment]
> I've found a fix for this based on this post https://stackoverflow.com/questions/40091136/cant-create-duplicate-variable-that-shadows-a-global-property. I changed `browser` to `Browser` and it now works OK in Safari.

Thanks! Can I ask which ones/what lines you changed? If I'm understanding correctly the `const` browser needs to change so it ≠ `var` value.

**Comment by lnlyssg** [comment]
As per my reply I changed all instances of browser (lowercase b) to Browser (uppercase B) - I didn't change anything else in the script.

**Comment by mgrimace** [comment]
> As per my reply I changed all instances of browser (lowercase b) to Browser (uppercase B) - I didn't change anything else in the script.

Thanks, ok, from what I can tell the following also works: setting the `var` as `Browser` on line 18020 (I only needed to change that line). Thanks for the lead, I'd have never found this otherwise

<img width="740" alt="Screen Shot 2024-03-01 at 11 30 41 AM" src="https://github.com/Snd-R/komf-userscript/assets/55518507/542b781d-6817-4b5e-8351-53d9eac88ae5">
