### ISSUE TITLE
[BUG] Manual search Background too dark

### ISSUE THREAD

**Issue by Eico-ccm** [Snd-R/komf-userscript#16]
Hello,

Thank you for your Work! I really like the use of Komf and the Userscript.

I've run into a Problem as i can't see the Title Names and Source Name in manual search. The Text is there but the Backgroud is too dark to see it directly (Picture below). Do you have an Idea what could be the cause? 
![Screenshot 2023-12-20 003038](https://github.com/Snd-R/komf-userscript/assets/78320722/cc1cc9e8-5b78-4be3-9ccb-276ee8da3f91)

Thank you for your Help!

Kind Regards,
Eico

Software Versions:
Userscript: 0.11.1
Komga: 1.9.2-master
Firefox: 121.0 (64-Bit)
Tampermonkey: 5.0.0

**Comment by Snd-R** [comment]
fixed in #19
