### ISSUE TITLE
Komga "Komf Settings" Connection Issue

### ISSUE THREAD

**Issue by benjamingrose1984** [Snd-R/komf-userscript#20]
![image](https://github.com/Snd-R/komf-userscript/assets/99149294/83ef1664-0a0a-4403-a823-107142794de8)
I'm pretty sure I'm solid up until the "Enter Komf URL" section.  I know I'm an idiot and I'm sorry if I'm failing at something so simple, but I have no Docker background and I'm failing at getting the non-JSScript section of this up and running.  This is the only thing I'm like 70% capable of completing, but I have no idea how to accomplish this last step.  Where the hell do I find the Komf URL?

**Comment by Snd-R** [comment]
You treat komf as a separate independent service that has its own address.
userscript allows to interact with that service. 

If you used example docker configuration from readme then komf url should be  `http://localhost:8085`
