### ISSUE TITLE
[Issue] Connection Failed

### ISSUE THREAD

**Issue by Pandoroz** [Snd-R/komf-userscript#22]
I installed Komga and the userscript correctly, but when configuring Komf to the server the connection failed, I tried in every way and searched the various sites/reddits to see if there was a solution but nothing. I'm using Opera GX and I tried with Chrome thinking it was a browser compatibility problem but nothing,
so it makes me think I'm doing something wrong or whatever.
(I also tried with Kavita, same problem)

**Comment by Snd-R** [comment]
On connection tab you need to input address of komf server.
Can you access your komf instance? it should be http://locahost:8085 by default

**Comment by Pandoroz** [comment]
Ok maybe I'm stupid, do I have to build Komf on my PC before installing the user-script? I thought about it now, I had totally forgotten about it actually...
Sorry for the inconvenience and waste of time
