### ISSUE TITLE
[Issue] Unable to identify series via komga

### ISSUE THREAD

**Issue by lavavex** [Snd-R/komf-userscript#23]
When using the userscript (to fix bad matches mostly) in komga, I am unable to search for the series as it gives an endpoint not found error
![image](https://github.com/Snd-R/komf-userscript/assets/27239435/130d40e1-0947-41da-a0ef-7e51b43e1d8b)
everything seems to work fine otherwise, but only the userscript causes this issue... I also dont have the Puzzle Piece icon to change settings for komf via komga ui, but the identify button does show.

**Comment by Snd-R** [comment]
Are you using latest userscript version? What browser and userscript manager are you using?
Don't really know why it would only partially work like this

**Comment by lavavex** [comment]
> Are you using latest userscript version? What browser and userscript manager are you using? Don't really know why it would only partially work like this

... i installed the extension via the search function of tampermonkey... it was running 0.1.0 of the script... installed version from github releases and is working fine now... sometimes i question how many braincells i actually have...
