### ISSUE TITLE
Manual Identification not working with Komf 1.0

### ISSUE THREAD

**Issue by orc4n** [Snd-R/komf-userscript#26]
The manual identification does not work anymore in Kavita, swapping
`app-series-detail app-side-nav-companion-bar div h2 span`
with 
`app-series-detail .info-container div h4 span`
should fix it (thanks Diesel on Discord!)

(this is mostly just a hint for other users who are not following the Discord channels etc.)

**Comment by kayhos** [comment]
Just to provide a bit more info, I believe this is meant to be performed in the userscript around line 39071.

Addenda for anyone looking to find versions to use: This fix with Kavita 0.8.3.0 and Komf 1.0.6 has manual identifcation functionnal again for me.

**Comment by Snd-R** [comment]
fixed in https://github.com/Snd-R/komf-userscript/releases/tag/0.12.2
