### ISSUE TITLE
Missing Providers?

### ISSUE THREAD

**Issue by Lumilicious** [Snd-R/komf-userscript#28]
Hello,

I have seen in your latest komf update notes that komf supports adult sources like Hentag to grab metadata, however I can't find a way to actually enable this in the user script (have tried to add hentag to config for example, but it's not showing up). I only see these

<img width="146" alt="11" src="https://github.com/user-attachments/assets/b51f983e-ec3a-4a24-96e5-bb068bb36fe0">

What am I doing wrong here? How do I enable Hentag? 

I run komf in docker on a Synology (pulled your docker container - https://registry.hub.docker.com/r/sndxr/komf/)

cheers

**Comment by Snd-R** [comment]
Yeah, It's not added to userscript yet. It should work even if it's not displayed in userscript.
For now you'll either need to manually edit the config file or use komf webui

**Comment by Lumilicious** [comment]
hmm.. I can't access any web-ui, I get a blank page when I try to access it. This may be a Synology issue, Synology and docker are kinda shit.

Anyway do you mean the application.yml config, I've already tried adding it by copying the lines from your example config, it's not working (heck I copied the whole thing). It's not super important if I can't get it to work myself, I now know that it's not a bug and just wait until it's implemented by you. 

Komf has been working great so far. Great job!

**Comment by Snd-R** [comment]
Webui is using canvas/wasm [Komelia](https://github.com/Snd-R/Komelia) application and not traditional html/js approach
It might not work on older safari or mobile browsers versions. Try updating your browser

**Comment by Lumilicious** [comment]
Oh wow, now I feel stupid. I never considered switching browsers for this as I never had any issues with Safari. 

The webui doesn't work with Safari 18.0.1 (newest version) and it also didn't work with Safari 17 (can't say if it worked with 16, I haven't been using komf for that long). I tried with a fresh profile, without add-ons and it's still a blank page. Same for Safari on iOS and iPadOS. I guess whatever browser rules the new Safari follows doesn't like komf's webui.

Works with ZenBrowser (Mozilla fork), though, was able to add Hentag to my library and it works now! Fantastic.

Thanks for nudging me into the right direction.

**Comment by Snd-R** [comment]
seems like Wasm garbage collection haven't reached mainline release yet. It will be available in 18.2 https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes#Web-Assembly
