### ISSUE TITLE
[Kavita] "See more" button disappear on summary page.

### ISSUE THREAD

**Issue by tanpro260196** [Snd-R/komf-userscript#5]
![image](https://user-images.githubusercontent.com/12226439/207492411-1e1eb58e-4825-4714-adb9-cc407778772a.png)
![image](https://user-images.githubusercontent.com/12226439/207492415-c8780d3d-edb1-4066-8070-521c4bde3445.png)

The "See More" button disappear.
Also everything on home is blue now.

**Comment by Snd-R** [comment]
fixed in https://github.com/Snd-R/komf-userscript/releases/tag/0.5.1
