### ISSUE TITLE
Failed to retrieve search results: Request failed with status code 404

### ISSUE THREAD

**Issue by soultaco83** [Snd-R/komf-userscript#6]
I have begun seeing the below errors
Failed to retrieve search results: Request failed with status code 404
Failed to match series: Request failed with status code 404

My script should be setup properly with the @include set as the following: 
// @include      http://192.168.108.208:8080/*

and the kofl-url set as following: 
  const komfUrl = useStorage("komf-url", "http://192.168.108.195:8085");

I am unsure on what the issue is now though. It was working and seemingly stopped communicating. I am just unsure on what this communication is that is failing.

**Comment by Snd-R** [comment]
You shouldn't use `useStorage()` function to set komf url. Url is stored in browser localstorage and changing default value in `useStorage()` will not change it after it was set. Instead use new settings menu

Komga:
![image](https://user-images.githubusercontent.com/76580768/210042925-57a96a55-5749-4860-b385-d4eec488b93f.png)
Kavita:
![image](https://user-images.githubusercontent.com/76580768/210043013-5d0e5acc-7a00-413f-93d7-dfc200085250.png)

If you really want to hardcode komf url then add  this after `// ==/UserScript==` 
`localStorage.setItem("komf-url", "http://192.168.108.195:8085");`

Though it would still be possible to change url from settings menu but after page reload these changes will be overwritten with your hardcoded value

**Comment by soultaco83** [comment]
Thank you. I reinstalled the script. Updated the url in the komf settings. This is now working.
