### ISSUE TITLE
Please add functional Updater URL.

### ISSUE THREAD

**Issue by arihid** [Snd-R/komf-userscript#8]
I'm using komf in combination with watchtower for zero-maintainance approach. But the script is not automatically updated in my browser, causing confusions as to why komf stopped working on browsers despite it running happily in docker.

My other scripts that was installed from greasyfork are receiving updates regularly.

Possible solution is to host this script to greasyfork in addition to this repo.

**Comment by Snd-R** [comment]
added update urls in latest release
Notice that if you edit userscript then autoupdate flag gets disabled in tampermonkey. (For example if you change @include section). You will need to re-enable it again in the userscript settings
